=begin
#Checkout.com API Reference

## Introduction Checkout.com provides a collection of APIs that enable you to process and manage payments.    Our APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors. You can consume the APIs directly using your favorite HTTP/REST library or make use of one of our <a href=\"https://docs.checkout.com/quickstart/integrate/sdks\" target=\"_blank\">SDKs</a>.    Our unified payments API allows you to accept payments from cards, digital wallets and the most popular alternative payment methods, as well as pay out to a variety of destinations, all using the same integration.  And with our webhook management, events and disputes APIs, you can keep on top of your transactions and react to any chargebacks, keeping your business running smoothly. # Authentication When you sign up for an account, you are given a secret and public API key pair. You authenticate with our API by providing the appropriate key in the request Authorization header.  Never share your secret keys. Keep them guarded and secure.   <!-- ReDoc-Inject: <security-definitions> --> 

The version of the OpenAPI document: 1.0.0
Contact: support@checkout.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Information required for 3D Secure payments
  class Model3dsRequest
    # Whether to process this payment as a 3D Secure payment
    attr_accessor :enabled

    # Determines whether to attempt a 3D Secure payment as non-3D Secure should the card issuer not be enrolled 
    attr_accessor :attempt_n3d

    # The Electronic Commerce Indicator security level associated with the 3D Secure enrollment result. Required if using a third-party merchant plug-in (MPI)
    attr_accessor :eci

    # A Base64 encoded cryptographic identifier (CAVV) used by the card schemes to validate the cardholder authentication result (3D Secure). Required if using an external MPI
    attr_accessor :cryptogram

    # The 3D Secure transaction identifier. Required if using an external MPI with 3D Secure 2.X.X and a Mastercard card, or with 3D Secure 1.X.X for any supported card scheme
    attr_accessor :xid

    # Indicates the version of 3D Secure that was used for authentication. Defaults to 1.0.0 if not provided
    attr_accessor :version

    # Specifies an exemption reason so that the payment is not processed using 3D Secure authentication. Learn more about exemptions in our <a href=\"https://docs.checkout.com/risk-management/sca-compliance-guide#SCAcomplianceguide-PossibleSCAexemptionsexemptions\">SCA compliance guide</a>.
    attr_accessor :exemption

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'enabled' => :'enabled',
        :'attempt_n3d' => :'attempt_n3d',
        :'eci' => :'eci',
        :'cryptogram' => :'cryptogram',
        :'xid' => :'xid',
        :'version' => :'version',
        :'exemption' => :'exemption'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'enabled' => :'Boolean',
        :'attempt_n3d' => :'Boolean',
        :'eci' => :'String',
        :'cryptogram' => :'String',
        :'xid' => :'String',
        :'version' => :'String',
        :'exemption' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Model3dsRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Model3dsRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'enabled')
        self.enabled = attributes[:'enabled']
      else
        self.enabled = false
      end

      if attributes.key?(:'attempt_n3d')
        self.attempt_n3d = attributes[:'attempt_n3d']
      else
        self.attempt_n3d = false
      end

      if attributes.key?(:'eci')
        self.eci = attributes[:'eci']
      end

      if attributes.key?(:'cryptogram')
        self.cryptogram = attributes[:'cryptogram']
      end

      if attributes.key?(:'xid')
        self.xid = attributes[:'xid']
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      end

      if attributes.key?(:'exemption')
        self.exemption = attributes[:'exemption']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@eci.nil? && @eci.to_s.length > 2
        invalid_properties.push('invalid value for "eci", the character length must be smaller than or equal to 2.')
      end

      if !@cryptogram.nil? && @cryptogram.to_s.length > 50
        invalid_properties.push('invalid value for "cryptogram", the character length must be smaller than or equal to 50.')
      end

      if !@xid.nil? && @xid.to_s.length > 100
        invalid_properties.push('invalid value for "xid", the character length must be smaller than or equal to 100.')
      end

      if !@version.nil? && @version.to_s.length > 10
        invalid_properties.push('invalid value for "version", the character length must be smaller than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@eci.nil? && @eci.to_s.length > 2
      return false if !@cryptogram.nil? && @cryptogram.to_s.length > 50
      return false if !@xid.nil? && @xid.to_s.length > 100
      return false if !@version.nil? && @version.to_s.length > 10
      exemption_validator = EnumAttributeValidator.new('String', ["low_value", "secure_corporate_payment", "trusted_listing"])
      return false unless exemption_validator.valid?(@exemption)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] eci Value to be assigned
    def eci=(eci)
      if !eci.nil? && eci.to_s.length > 2
        fail ArgumentError, 'invalid value for "eci", the character length must be smaller than or equal to 2.'
      end

      @eci = eci
    end

    # Custom attribute writer method with validation
    # @param [Object] cryptogram Value to be assigned
    def cryptogram=(cryptogram)
      if !cryptogram.nil? && cryptogram.to_s.length > 50
        fail ArgumentError, 'invalid value for "cryptogram", the character length must be smaller than or equal to 50.'
      end

      @cryptogram = cryptogram
    end

    # Custom attribute writer method with validation
    # @param [Object] xid Value to be assigned
    def xid=(xid)
      if !xid.nil? && xid.to_s.length > 100
        fail ArgumentError, 'invalid value for "xid", the character length must be smaller than or equal to 100.'
      end

      @xid = xid
    end

    # Custom attribute writer method with validation
    # @param [Object] version Value to be assigned
    def version=(version)
      if !version.nil? && version.to_s.length > 10
        fail ArgumentError, 'invalid value for "version", the character length must be smaller than or equal to 10.'
      end

      @version = version
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] exemption Object to be assigned
    def exemption=(exemption)
      validator = EnumAttributeValidator.new('String', ["low_value", "secure_corporate_payment", "trusted_listing"])
      unless validator.valid?(exemption)
        fail ArgumentError, "invalid value for \"exemption\", must be one of #{validator.allowable_values}."
      end
      @exemption = exemption
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          enabled == o.enabled &&
          attempt_n3d == o.attempt_n3d &&
          eci == o.eci &&
          cryptogram == o.cryptogram &&
          xid == o.xid &&
          version == o.version &&
          exemption == o.exemption
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [enabled, attempt_n3d, eci, cryptogram, xid, version, exemption].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
