=begin
#Checkout.com API Reference

## Introduction Checkout.com provides a collection of APIs that enable you to process and manage payments.    Our APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors. You can consume the APIs directly using your favorite HTTP/REST library or make use of one of our <a href=\"https://docs.checkout.com/quickstart/integrate/sdks\" target=\"_blank\">SDKs</a>.    Our unified payments API allows you to accept payments from cards, digital wallets and the most popular alternative payment methods, as well as pay out to a variety of destinations, all using the same integration.  And with our webhook management, events and disputes APIs, you can keep on top of your transactions and react to any chargebacks, keeping your business running smoothly. # Authentication When you sign up for an account, you are given a secret and public API key pair. You authenticate with our API by providing the appropriate key in the request Authorization header.  Never share your secret keys. Keep them guarded and secure.   <!-- ReDoc-Inject: <security-definitions> --> 

The version of the OpenAPI document: 1.0.0
Contact: support@checkout.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PaymentRequest
    attr_accessor :source

    # The payment amount. The exact format <a href=\"https://docs.checkout.com/resources/calculating-the-value\" target=\"blank\">depends on the currency</a>. Omit the amount or provide a value of `0` to perform a card verification.  
    attr_accessor :amount

    # The three-letter <a href=\"https://docs.checkout.com/resources/codes/currency-codes\" target=\"blank\">ISO currency code</a> 
    attr_accessor :currency

    # This must be specified for card payments where the cardholder is not present (i.e., recurring or mail order / telephone order)
    attr_accessor :payment_type

    # Flags the payment as a merchant-initiated transaction (MIT). <a href=\"https://docs.checkout.com/quickstart/use-an-existing-card/stored-card-details\" target=\"_blank\">Must be set to `true` for all MITs</a>.
    attr_accessor :merchant_initiated

    # A reference you can later use to identify this payment, such as an order number. Required when processing via dLocal or Bambora.
    attr_accessor :reference

    # A description of the payment
    attr_accessor :description

    # Whether to capture the payment (if applicable)
    attr_accessor :capture

    # A timestamp (ISO 8601 code) that determines when the payment should be captured. Providing this field will automatically set `capture` to true 
    attr_accessor :capture_on

    attr_accessor :customer

    attr_accessor :billing_descriptor

    attr_accessor :shipping

    attr_accessor :_3ds

    # For payments that use <a href=\"https://docs.checkout.com/quickstart/use-an-existing-card/stored-card-details\" target=\"blank\">stored card details</a>, such as recurring payments â€“ an existing payment identifier from the recurring series or the Scheme Transaction Id 
    attr_accessor :previous_payment_id

    attr_accessor :risk

    # For redirect payment methods, this overrides the default success redirect URL configured on your account
    attr_accessor :success_url

    # For redirect payment methods, this overrides the default failure redirect URL configured on your account
    attr_accessor :failure_url

    # The IP address used to make the payment. Required for some risk checks
    attr_accessor :payment_ip

    attr_accessor :recipient

    attr_accessor :processing

    # Allows you to store additional information about a transaction with custom fields and up to five user-defined fields (`udf1` to `udf5`), which can be used for reporting purposes. `udf1` is also used for some of our risk rules.
    attr_accessor :metadata

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'source' => :'source',
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'payment_type' => :'payment_type',
        :'merchant_initiated' => :'merchant_initiated',
        :'reference' => :'reference',
        :'description' => :'description',
        :'capture' => :'capture',
        :'capture_on' => :'capture_on',
        :'customer' => :'customer',
        :'billing_descriptor' => :'billing_descriptor',
        :'shipping' => :'shipping',
        :'_3ds' => :'3ds',
        :'previous_payment_id' => :'previous_payment_id',
        :'risk' => :'risk',
        :'success_url' => :'success_url',
        :'failure_url' => :'failure_url',
        :'payment_ip' => :'payment_ip',
        :'recipient' => :'recipient',
        :'processing' => :'processing',
        :'metadata' => :'metadata'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'source' => :'PaymentRequestSource',
        :'amount' => :'Integer',
        :'currency' => :'String',
        :'payment_type' => :'String',
        :'merchant_initiated' => :'Boolean',
        :'reference' => :'String',
        :'description' => :'String',
        :'capture' => :'Boolean',
        :'capture_on' => :'Time',
        :'customer' => :'PaymentRequestCustomer',
        :'billing_descriptor' => :'BillingDescriptor',
        :'shipping' => :'PaymentRequestShipping',
        :'_3ds' => :'Model3dsRequest',
        :'previous_payment_id' => :'String',
        :'risk' => :'RiskRequest',
        :'success_url' => :'String',
        :'failure_url' => :'String',
        :'payment_ip' => :'String',
        :'recipient' => :'PaymentRecipient',
        :'processing' => :'PaymentRequestProcessing',
        :'metadata' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PaymentRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PaymentRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'payment_type')
        self.payment_type = attributes[:'payment_type']
      else
        self.payment_type = 'Regular'
      end

      if attributes.key?(:'merchant_initiated')
        self.merchant_initiated = attributes[:'merchant_initiated']
      end

      if attributes.key?(:'reference')
        self.reference = attributes[:'reference']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'capture')
        self.capture = attributes[:'capture']
      else
        self.capture = true
      end

      if attributes.key?(:'capture_on')
        self.capture_on = attributes[:'capture_on']
      end

      if attributes.key?(:'customer')
        self.customer = attributes[:'customer']
      end

      if attributes.key?(:'billing_descriptor')
        self.billing_descriptor = attributes[:'billing_descriptor']
      end

      if attributes.key?(:'shipping')
        self.shipping = attributes[:'shipping']
      end

      if attributes.key?(:'_3ds')
        self._3ds = attributes[:'_3ds']
      end

      if attributes.key?(:'previous_payment_id')
        self.previous_payment_id = attributes[:'previous_payment_id']
      end

      if attributes.key?(:'risk')
        self.risk = attributes[:'risk']
      end

      if attributes.key?(:'success_url')
        self.success_url = attributes[:'success_url']
      end

      if attributes.key?(:'failure_url')
        self.failure_url = attributes[:'failure_url']
      end

      if attributes.key?(:'payment_ip')
        self.payment_ip = attributes[:'payment_ip']
      end

      if attributes.key?(:'recipient')
        self.recipient = attributes[:'recipient']
      end

      if attributes.key?(:'processing')
        self.processing = attributes[:'processing']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@amount.nil? && @amount < 0
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @currency.to_s.length > 3
        invalid_properties.push('invalid value for "currency", the character length must be smaller than or equal to 3.')
      end

      if @currency.to_s.length < 3
        invalid_properties.push('invalid value for "currency", the character length must be great than or equal to 3.')
      end

      if !@reference.nil? && @reference.to_s.length > 50
        invalid_properties.push('invalid value for "reference", the character length must be smaller than or equal to 50.')
      end

      if !@description.nil? && @description.to_s.length > 100
        invalid_properties.push('invalid value for "description", the character length must be smaller than or equal to 100.')
      end

      if !@previous_payment_id.nil? && @previous_payment_id.to_s.length > 100
        invalid_properties.push('invalid value for "previous_payment_id", the character length must be smaller than or equal to 100.')
      end

      if !@success_url.nil? && @success_url.to_s.length > 255
        invalid_properties.push('invalid value for "success_url", the character length must be smaller than or equal to 255.')
      end

      if !@failure_url.nil? && @failure_url.to_s.length > 255
        invalid_properties.push('invalid value for "failure_url", the character length must be smaller than or equal to 255.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@amount.nil? && @amount < 0
      return false if @currency.nil?
      return false if @currency.to_s.length > 3
      return false if @currency.to_s.length < 3
      payment_type_validator = EnumAttributeValidator.new('String', ["Regular", "Recurring", "MOTO"])
      return false unless payment_type_validator.valid?(@payment_type)
      return false if !@reference.nil? && @reference.to_s.length > 50
      return false if !@description.nil? && @description.to_s.length > 100
      return false if !@previous_payment_id.nil? && @previous_payment_id.to_s.length > 100
      return false if !@success_url.nil? && @success_url.to_s.length > 255
      return false if !@failure_url.nil? && @failure_url.to_s.length > 255
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if !amount.nil? && amount < 0
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      if currency.to_s.length > 3
        fail ArgumentError, 'invalid value for "currency", the character length must be smaller than or equal to 3.'
      end

      if currency.to_s.length < 3
        fail ArgumentError, 'invalid value for "currency", the character length must be great than or equal to 3.'
      end

      @currency = currency
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payment_type Object to be assigned
    def payment_type=(payment_type)
      validator = EnumAttributeValidator.new('String', ["Regular", "Recurring", "MOTO"])
      unless validator.valid?(payment_type)
        fail ArgumentError, "invalid value for \"payment_type\", must be one of #{validator.allowable_values}."
      end
      @payment_type = payment_type
    end

    # Custom attribute writer method with validation
    # @param [Object] reference Value to be assigned
    def reference=(reference)
      if !reference.nil? && reference.to_s.length > 50
        fail ArgumentError, 'invalid value for "reference", the character length must be smaller than or equal to 50.'
      end

      @reference = reference
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if !description.nil? && description.to_s.length > 100
        fail ArgumentError, 'invalid value for "description", the character length must be smaller than or equal to 100.'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] previous_payment_id Value to be assigned
    def previous_payment_id=(previous_payment_id)
      if !previous_payment_id.nil? && previous_payment_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "previous_payment_id", the character length must be smaller than or equal to 100.'
      end

      @previous_payment_id = previous_payment_id
    end

    # Custom attribute writer method with validation
    # @param [Object] success_url Value to be assigned
    def success_url=(success_url)
      if !success_url.nil? && success_url.to_s.length > 255
        fail ArgumentError, 'invalid value for "success_url", the character length must be smaller than or equal to 255.'
      end

      @success_url = success_url
    end

    # Custom attribute writer method with validation
    # @param [Object] failure_url Value to be assigned
    def failure_url=(failure_url)
      if !failure_url.nil? && failure_url.to_s.length > 255
        fail ArgumentError, 'invalid value for "failure_url", the character length must be smaller than or equal to 255.'
      end

      @failure_url = failure_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          source == o.source &&
          amount == o.amount &&
          currency == o.currency &&
          payment_type == o.payment_type &&
          merchant_initiated == o.merchant_initiated &&
          reference == o.reference &&
          description == o.description &&
          capture == o.capture &&
          capture_on == o.capture_on &&
          customer == o.customer &&
          billing_descriptor == o.billing_descriptor &&
          shipping == o.shipping &&
          _3ds == o._3ds &&
          previous_payment_id == o.previous_payment_id &&
          risk == o.risk &&
          success_url == o.success_url &&
          failure_url == o.failure_url &&
          payment_ip == o.payment_ip &&
          recipient == o.recipient &&
          processing == o.processing &&
          metadata == o.metadata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [source, amount, currency, payment_type, merchant_initiated, reference, description, capture, capture_on, customer, billing_descriptor, shipping, _3ds, previous_payment_id, risk, success_url, failure_url, payment_ip, recipient, processing, metadata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
