=begin
#Checkout.com API Reference

## Introduction Checkout.com provides a collection of APIs that enable you to process and manage payments.    Our APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors. You can consume the APIs directly using your favorite HTTP/REST library or make use of one of our <a href=\"https://docs.checkout.com/quickstart/integrate/sdks\" target=\"_blank\">SDKs</a>.    Our unified payments API allows you to accept payments from cards, digital wallets and the most popular alternative payment methods, as well as pay out to a variety of destinations, all using the same integration.  And with our webhook management, events and disputes APIs, you can keep on top of your transactions and react to any chargebacks, keeping your business running smoothly. # Authentication When you sign up for an account, you are given a secret and public API key pair. You authenticate with our API by providing the appropriate key in the request Authorization header.  Never share your secret keys. Keep them guarded and secure.   <!-- ReDoc-Inject: <security-definitions> --> 

The version of the OpenAPI document: 1.0.0
Contact: support@checkout.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'date'
require 'time'

module OpenapiClient
  # KNet Source
  class PaymentResponseKnetSource < PaymentResponseSource
    # This field enables the Issuer's site to select the Consumer's preferred language (e.g. the language selected on the Merchant's site), if the Issuer's site supports this. Code list in accordance with ISO 639-1. (Arabic = 'ar', English = 'en'). NOTE: 'ar' corresponds to 'ARA' and 'en' - to 'USA' values accepted by KNet Gateway.
    attr_accessor :language

    # User defined field can be used to pass and store any additional transaction data required to be archived with the transaction and available as a searching criteria. Only alphanumeric characters and spaces are allowed.
    attr_accessor :user_defined_field1

    # User defined field can be used to pass and store any additional transaction data required to be archived with the transaction and available as a searching criteria. Only alphanumeric characters and spaces are allowed.
    attr_accessor :user_defined_field2

    # User defined field can be used to pass and store any additional transaction data required to be archived with the transaction and available as a searching criteria. Only alphanumeric characters and spaces are allowed. Note that this field must be omitted when the card_token field is not empty. This restriction exists because a card token is passed to KNet Gateway as user defined field 3.
    attr_accessor :user_defined_field3

    # User defined field can be used to pass and store any additional transaction data required to be archived with the transaction and available as a searching criteria. Only alphanumeric characters and spaces are allowed.
    attr_accessor :user_defined_field4

    # User defined field can be used to pass and store any additional transaction data required to be archived with the transaction and available as a searching criteria. Only alphanumeric characters and spaces are allowed. Note that this field must be omitted when the ptlf field is not empty. This restriction exists because a PTLF value is passed to KNet Gateway as user defined field 5.
    attr_accessor :user_defined_field5

    # This token allows re-usage of card details for multiple payments. This 8-digit token should be generated by a merchant. When a subsequent payment is initialized with the same card token, a customer is presented with two options. The customer can choose to pay with KFast (doesn't need to enter card details again), or with KNet as usual. The payment flow stays the same i.e. a merchant should redirect a customer to the redirect URL which is provided in the payment creation response. Note that user_defined_field3 must be omitted when the card_token field is not empty. This restriction exists because a card token is passed to KNet Gateway as user defined field 3.
    attr_accessor :card_token

    # This is an ID for merchant PTLF functionality tracking. Only alphanumeric characters are allowed. Note that user_defined_field5 must be omitted when the ptlf field is not empty. This restriction exists because a PTLF value is passed to KNet Gateway as user defined field 5.
    attr_accessor :ptlf

    # The payment identifier assigned by KNet Gateway.
    attr_accessor :knet_payment_id

    # The state of the payment, returned by KNet Gateway after the customer is redirected from the payment page.
    attr_accessor :knet_result

    # The state of the payment, retunrned by KNet Gateway in the response from the payment inquiry. This field is populated in rare cases when the redirection from the payment page did not occur properly.
    attr_accessor :inquiry_result

    # The result transaction reference, given by some banks/institutions.
    attr_accessor :bank_reference

    # The transaction identifier assigned by KNet Gateway.
    attr_accessor :knet_transaction_id

    # The resulting authorization code from the issuing bank.
    attr_accessor :auth_code

    # The auth response code / reason code relating to the issuing bank authorization code.
    attr_accessor :auth_response_code

    # The transaction date in the authorization system format, with the value defined by the issuing bank, so may not match the actual transaction date. The format is `MMDD`.
    attr_accessor :post_date

    # The Address Verification Response returned from the address verification service.
    attr_accessor :avr

    # The KNET error code for transaction processing.
    attr_accessor :error

    # The KNET text detail for the error, including an error code.
    attr_accessor :error_text

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'language' => :'language',
        :'user_defined_field1' => :'user_defined_field1',
        :'user_defined_field2' => :'user_defined_field2',
        :'user_defined_field3' => :'user_defined_field3',
        :'user_defined_field4' => :'user_defined_field4',
        :'user_defined_field5' => :'user_defined_field5',
        :'card_token' => :'card_token',
        :'ptlf' => :'ptlf',
        :'knet_payment_id' => :'knet_payment_id',
        :'knet_result' => :'knet_result',
        :'inquiry_result' => :'inquiry_result',
        :'bank_reference' => :'bank_reference',
        :'knet_transaction_id' => :'knet_transaction_id',
        :'auth_code' => :'auth_code',
        :'auth_response_code' => :'auth_response_code',
        :'post_date' => :'post_date',
        :'avr' => :'avr',
        :'error' => :'error',
        :'error_text' => :'error_text'
      }
    end

    # Returns all the JSON keys this model knows about, including the ones defined in its parent(s)
    def self.acceptable_attributes
      attribute_map.values.concat(superclass.acceptable_attributes)
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'language' => :'String',
        :'user_defined_field1' => :'String',
        :'user_defined_field2' => :'String',
        :'user_defined_field3' => :'String',
        :'user_defined_field4' => :'String',
        :'user_defined_field5' => :'String',
        :'card_token' => :'String',
        :'ptlf' => :'String',
        :'knet_payment_id' => :'String',
        :'knet_result' => :'String',
        :'inquiry_result' => :'String',
        :'bank_reference' => :'String',
        :'knet_transaction_id' => :'String',
        :'auth_code' => :'String',
        :'auth_response_code' => :'String',
        :'post_date' => :'String',
        :'avr' => :'String',
        :'error' => :'String',
        :'error_text' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'PaymentResponseKnetSourceAllOf',
      :'PaymentResponseSource'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PaymentResponseKnetSource` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PaymentResponseKnetSource`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      # call parent's initialize
      super(attributes)

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'user_defined_field1')
        self.user_defined_field1 = attributes[:'user_defined_field1']
      end

      if attributes.key?(:'user_defined_field2')
        self.user_defined_field2 = attributes[:'user_defined_field2']
      end

      if attributes.key?(:'user_defined_field3')
        self.user_defined_field3 = attributes[:'user_defined_field3']
      end

      if attributes.key?(:'user_defined_field4')
        self.user_defined_field4 = attributes[:'user_defined_field4']
      end

      if attributes.key?(:'user_defined_field5')
        self.user_defined_field5 = attributes[:'user_defined_field5']
      end

      if attributes.key?(:'card_token')
        self.card_token = attributes[:'card_token']
      end

      if attributes.key?(:'ptlf')
        self.ptlf = attributes[:'ptlf']
      end

      if attributes.key?(:'knet_payment_id')
        self.knet_payment_id = attributes[:'knet_payment_id']
      end

      if attributes.key?(:'knet_result')
        self.knet_result = attributes[:'knet_result']
      end

      if attributes.key?(:'inquiry_result')
        self.inquiry_result = attributes[:'inquiry_result']
      end

      if attributes.key?(:'bank_reference')
        self.bank_reference = attributes[:'bank_reference']
      end

      if attributes.key?(:'knet_transaction_id')
        self.knet_transaction_id = attributes[:'knet_transaction_id']
      end

      if attributes.key?(:'auth_code')
        self.auth_code = attributes[:'auth_code']
      end

      if attributes.key?(:'auth_response_code')
        self.auth_response_code = attributes[:'auth_response_code']
      end

      if attributes.key?(:'post_date')
        self.post_date = attributes[:'post_date']
      end

      if attributes.key?(:'avr')
        self.avr = attributes[:'avr']
      end

      if attributes.key?(:'error')
        self.error = attributes[:'error']
      end

      if attributes.key?(:'error_text')
        self.error_text = attributes[:'error_text']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = super
      pattern = Regexp.new(/^[0-9]{8}$/)
      if !@card_token.nil? && @card_token !~ pattern
        invalid_properties.push("invalid value for \"card_token\", must conform to the pattern #{pattern}.")
      end

      if !@ptlf.nil? && @ptlf.to_s.length > 45
        invalid_properties.push('invalid value for "ptlf", the character length must be smaller than or equal to 45.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      language_validator = EnumAttributeValidator.new('String', ["ar", "en"])
      return false unless language_validator.valid?(@language)
      return false if !@card_token.nil? && @card_token !~ Regexp.new(/^[0-9]{8}$/)
      return false if !@ptlf.nil? && @ptlf.to_s.length > 45
      true && super
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] language Object to be assigned
    def language=(language)
      validator = EnumAttributeValidator.new('String', ["ar", "en"])
      unless validator.valid?(language)
        fail ArgumentError, "invalid value for \"language\", must be one of #{validator.allowable_values}."
      end
      @language = language
    end

    # Custom attribute writer method with validation
    # @param [Object] card_token Value to be assigned
    def card_token=(card_token)
      pattern = Regexp.new(/^[0-9]{8}$/)
      if !card_token.nil? && card_token !~ pattern
        fail ArgumentError, "invalid value for \"card_token\", must conform to the pattern #{pattern}."
      end

      @card_token = card_token
    end

    # Custom attribute writer method with validation
    # @param [Object] ptlf Value to be assigned
    def ptlf=(ptlf)
      if !ptlf.nil? && ptlf.to_s.length > 45
        fail ArgumentError, 'invalid value for "ptlf", the character length must be smaller than or equal to 45.'
      end

      @ptlf = ptlf
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          language == o.language &&
          user_defined_field1 == o.user_defined_field1 &&
          user_defined_field2 == o.user_defined_field2 &&
          user_defined_field3 == o.user_defined_field3 &&
          user_defined_field4 == o.user_defined_field4 &&
          user_defined_field5 == o.user_defined_field5 &&
          card_token == o.card_token &&
          ptlf == o.ptlf &&
          knet_payment_id == o.knet_payment_id &&
          knet_result == o.knet_result &&
          inquiry_result == o.inquiry_result &&
          bank_reference == o.bank_reference &&
          knet_transaction_id == o.knet_transaction_id &&
          auth_code == o.auth_code &&
          auth_response_code == o.auth_response_code &&
          post_date == o.post_date &&
          avr == o.avr &&
          error == o.error &&
          error_text == o.error_text && super(o)
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [language, user_defined_field1, user_defined_field2, user_defined_field3, user_defined_field4, user_defined_field5, card_token, ptlf, knet_payment_id, knet_result, inquiry_result, bank_reference, knet_transaction_id, auth_code, auth_response_code, post_date, avr, error, error_text].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      super(attributes)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = super
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
