=begin
#Checkout.com API Reference

## Introduction Checkout.com provides a collection of APIs that enable you to process and manage payments.    Our APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors. You can consume the APIs directly using your favorite HTTP/REST library or make use of one of our <a href=\"https://docs.checkout.com/quickstart/integrate/sdks\" target=\"_blank\">SDKs</a>.    Our unified payments API allows you to accept payments from cards, digital wallets and the most popular alternative payment methods, as well as pay out to a variety of destinations, all using the same integration.  And with our webhook management, events and disputes APIs, you can keep on top of your transactions and react to any chargebacks, keeping your business running smoothly. # Authentication When you sign up for an account, you are given a secret and public API key pair. You authenticate with our API by providing the appropriate key in the request Authorization header.  Never share your secret keys. Keep them guarded and secure.   <!-- ReDoc-Inject: <security-definitions> --> 

The version of the OpenAPI document: 1.0.0
Contact: support@checkout.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ProvideEvidenceRequest
    # A file containing proof of delivery of goods or services
    attr_accessor :proof_of_delivery_or_service_file

    # A brief text description of the file. You can also use this field to provide a link
    attr_accessor :proof_of_delivery_or_service_text

    # A file containing an invoice/receipt
    attr_accessor :invoice_or_receipt_file

    # A brief text description of the file. You can also use this field to provide a link
    attr_accessor :invoice_or_receipt_text

    # A file containing invoice showing two distinct transactions
    attr_accessor :invoice_showing_distinct_transactions_file

    # A brief text description of the file. You can also use this field to provide a link
    attr_accessor :invoice_showing_distinct_transactions_text

    # A file containing customer cummunication
    attr_accessor :customer_communication_file

    # A brief text description of the file. You can also use this field to provide a link
    attr_accessor :customer_communication_text

    # A file containing refund/cancellation policy
    attr_accessor :refund_or_cancellation_policy_file

    # A brief text description of the file. You can also use this field to provide a link
    attr_accessor :refund_or_cancellation_policy_text

    # A file containing the recurring transaction agreement
    attr_accessor :recurring_transaction_agreement_file

    # A brief text description of the file. You can also use this field to provide a link
    attr_accessor :recurring_transaction_agreement_text

    # A file containing additional supporting documents
    attr_accessor :additional_evidence_file

    # A brief text description of the file. You can also use this field to provide a link
    attr_accessor :additional_evidence_text

    # A file showing the delivery date of the provided service/merchandise
    attr_accessor :proof_of_delivery_or_service_date_file

    # A brief text description of the file. You can also use this field to provide a link
    attr_accessor :proof_of_delivery_or_service_date_text

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'proof_of_delivery_or_service_file' => :'proof_of_delivery_or_service_file',
        :'proof_of_delivery_or_service_text' => :'proof_of_delivery_or_service_text',
        :'invoice_or_receipt_file' => :'invoice_or_receipt_file',
        :'invoice_or_receipt_text' => :'invoice_or_receipt_text',
        :'invoice_showing_distinct_transactions_file' => :'invoice_showing_distinct_transactions_file',
        :'invoice_showing_distinct_transactions_text' => :'invoice_showing_distinct_transactions_text',
        :'customer_communication_file' => :'customer_communication_file',
        :'customer_communication_text' => :'customer_communication_text',
        :'refund_or_cancellation_policy_file' => :'refund_or_cancellation_policy_file',
        :'refund_or_cancellation_policy_text' => :'refund_or_cancellation_policy_text',
        :'recurring_transaction_agreement_file' => :'recurring_transaction_agreement_file',
        :'recurring_transaction_agreement_text' => :'recurring_transaction_agreement_text',
        :'additional_evidence_file' => :'additional_evidence_file',
        :'additional_evidence_text' => :'additional_evidence_text',
        :'proof_of_delivery_or_service_date_file' => :'proof_of_delivery_or_service_date_file',
        :'proof_of_delivery_or_service_date_text' => :'proof_of_delivery_or_service_date_text'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'proof_of_delivery_or_service_file' => :'String',
        :'proof_of_delivery_or_service_text' => :'String',
        :'invoice_or_receipt_file' => :'String',
        :'invoice_or_receipt_text' => :'String',
        :'invoice_showing_distinct_transactions_file' => :'String',
        :'invoice_showing_distinct_transactions_text' => :'String',
        :'customer_communication_file' => :'String',
        :'customer_communication_text' => :'String',
        :'refund_or_cancellation_policy_file' => :'String',
        :'refund_or_cancellation_policy_text' => :'String',
        :'recurring_transaction_agreement_file' => :'String',
        :'recurring_transaction_agreement_text' => :'String',
        :'additional_evidence_file' => :'String',
        :'additional_evidence_text' => :'String',
        :'proof_of_delivery_or_service_date_file' => :'String',
        :'proof_of_delivery_or_service_date_text' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ProvideEvidenceRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ProvideEvidenceRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'proof_of_delivery_or_service_file')
        self.proof_of_delivery_or_service_file = attributes[:'proof_of_delivery_or_service_file']
      end

      if attributes.key?(:'proof_of_delivery_or_service_text')
        self.proof_of_delivery_or_service_text = attributes[:'proof_of_delivery_or_service_text']
      end

      if attributes.key?(:'invoice_or_receipt_file')
        self.invoice_or_receipt_file = attributes[:'invoice_or_receipt_file']
      end

      if attributes.key?(:'invoice_or_receipt_text')
        self.invoice_or_receipt_text = attributes[:'invoice_or_receipt_text']
      end

      if attributes.key?(:'invoice_showing_distinct_transactions_file')
        self.invoice_showing_distinct_transactions_file = attributes[:'invoice_showing_distinct_transactions_file']
      end

      if attributes.key?(:'invoice_showing_distinct_transactions_text')
        self.invoice_showing_distinct_transactions_text = attributes[:'invoice_showing_distinct_transactions_text']
      end

      if attributes.key?(:'customer_communication_file')
        self.customer_communication_file = attributes[:'customer_communication_file']
      end

      if attributes.key?(:'customer_communication_text')
        self.customer_communication_text = attributes[:'customer_communication_text']
      end

      if attributes.key?(:'refund_or_cancellation_policy_file')
        self.refund_or_cancellation_policy_file = attributes[:'refund_or_cancellation_policy_file']
      end

      if attributes.key?(:'refund_or_cancellation_policy_text')
        self.refund_or_cancellation_policy_text = attributes[:'refund_or_cancellation_policy_text']
      end

      if attributes.key?(:'recurring_transaction_agreement_file')
        self.recurring_transaction_agreement_file = attributes[:'recurring_transaction_agreement_file']
      end

      if attributes.key?(:'recurring_transaction_agreement_text')
        self.recurring_transaction_agreement_text = attributes[:'recurring_transaction_agreement_text']
      end

      if attributes.key?(:'additional_evidence_file')
        self.additional_evidence_file = attributes[:'additional_evidence_file']
      end

      if attributes.key?(:'additional_evidence_text')
        self.additional_evidence_text = attributes[:'additional_evidence_text']
      end

      if attributes.key?(:'proof_of_delivery_or_service_date_file')
        self.proof_of_delivery_or_service_date_file = attributes[:'proof_of_delivery_or_service_date_file']
      end

      if attributes.key?(:'proof_of_delivery_or_service_date_text')
        self.proof_of_delivery_or_service_date_text = attributes[:'proof_of_delivery_or_service_date_text']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] proof_of_delivery_or_service_text Value to be assigned
    def proof_of_delivery_or_service_text=(proof_of_delivery_or_service_text)
      @proof_of_delivery_or_service_text = proof_of_delivery_or_service_text
    end

    # Custom attribute writer method with validation
    # @param [Object] invoice_or_receipt_text Value to be assigned
    def invoice_or_receipt_text=(invoice_or_receipt_text)
      @invoice_or_receipt_text = invoice_or_receipt_text
    end

    # Custom attribute writer method with validation
    # @param [Object] invoice_showing_distinct_transactions_text Value to be assigned
    def invoice_showing_distinct_transactions_text=(invoice_showing_distinct_transactions_text)
      @invoice_showing_distinct_transactions_text = invoice_showing_distinct_transactions_text
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_communication_text Value to be assigned
    def customer_communication_text=(customer_communication_text)
      @customer_communication_text = customer_communication_text
    end

    # Custom attribute writer method with validation
    # @param [Object] refund_or_cancellation_policy_text Value to be assigned
    def refund_or_cancellation_policy_text=(refund_or_cancellation_policy_text)
      @refund_or_cancellation_policy_text = refund_or_cancellation_policy_text
    end

    # Custom attribute writer method with validation
    # @param [Object] recurring_transaction_agreement_text Value to be assigned
    def recurring_transaction_agreement_text=(recurring_transaction_agreement_text)
      @recurring_transaction_agreement_text = recurring_transaction_agreement_text
    end

    # Custom attribute writer method with validation
    # @param [Object] additional_evidence_text Value to be assigned
    def additional_evidence_text=(additional_evidence_text)
      @additional_evidence_text = additional_evidence_text
    end

    # Custom attribute writer method with validation
    # @param [Object] proof_of_delivery_or_service_date_text Value to be assigned
    def proof_of_delivery_or_service_date_text=(proof_of_delivery_or_service_date_text)
      @proof_of_delivery_or_service_date_text = proof_of_delivery_or_service_date_text
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          proof_of_delivery_or_service_file == o.proof_of_delivery_or_service_file &&
          proof_of_delivery_or_service_text == o.proof_of_delivery_or_service_text &&
          invoice_or_receipt_file == o.invoice_or_receipt_file &&
          invoice_or_receipt_text == o.invoice_or_receipt_text &&
          invoice_showing_distinct_transactions_file == o.invoice_showing_distinct_transactions_file &&
          invoice_showing_distinct_transactions_text == o.invoice_showing_distinct_transactions_text &&
          customer_communication_file == o.customer_communication_file &&
          customer_communication_text == o.customer_communication_text &&
          refund_or_cancellation_policy_file == o.refund_or_cancellation_policy_file &&
          refund_or_cancellation_policy_text == o.refund_or_cancellation_policy_text &&
          recurring_transaction_agreement_file == o.recurring_transaction_agreement_file &&
          recurring_transaction_agreement_text == o.recurring_transaction_agreement_text &&
          additional_evidence_file == o.additional_evidence_file &&
          additional_evidence_text == o.additional_evidence_text &&
          proof_of_delivery_or_service_date_file == o.proof_of_delivery_or_service_date_file &&
          proof_of_delivery_or_service_date_text == o.proof_of_delivery_or_service_date_text
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [proof_of_delivery_or_service_file, proof_of_delivery_or_service_text, invoice_or_receipt_file, invoice_or_receipt_text, invoice_showing_distinct_transactions_file, invoice_showing_distinct_transactions_text, customer_communication_file, customer_communication_text, refund_or_cancellation_policy_file, refund_or_cancellation_policy_text, recurring_transaction_agreement_file, recurring_transaction_agreement_text, additional_evidence_file, additional_evidence_text, proof_of_delivery_or_service_date_file, proof_of_delivery_or_service_date_text].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
