=begin
#Checkout.com API Reference

## Introduction Checkout.com provides a collection of APIs that enable you to process and manage payments.    Our APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors. You can consume the APIs directly using your favorite HTTP/REST library or make use of one of our <a href=\"https://docs.checkout.com/quickstart/integrate/sdks\" target=\"_blank\">SDKs</a>.    Our unified payments API allows you to accept payments from cards, digital wallets and the most popular alternative payment methods, as well as pay out to a variety of destinations, all using the same integration.  And with our webhook management, events and disputes APIs, you can keep on top of your transactions and react to any chargebacks, keeping your business running smoothly. # Authentication When you sign up for an account, you are given a secret and public API key pair. You authenticate with our API by providing the appropriate key in the request Authorization header.  Never share your secret keys. Keep them guarded and secure.   <!-- ReDoc-Inject: <security-definitions> --> 

The version of the OpenAPI document: 1.0.0
Contact: support@checkout.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SourcesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SourcesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SourcesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SourcesApi' do
    it 'should create an instance of SourcesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SourcesApi)
    end
  end

  # unit tests for add_a_payment_source
  # Add a payment source
  # Add a reusable payment source, like a &lt;a href&#x3D;\&quot;https://docs.checkout.com/payment-methods/direct-debit/sepa-direct-debit\&quot; target&#x3D;\&quot;blank\&quot;&gt;SEPA Direct Debit&lt;/a&gt;, that you can later use to make one or more payments. Payment sources are linked to a specific customer and cannot be shared between customers. 
  # @param [Hash] opts the optional parameters
  # @option opts [SourceRequest] :source_request 
  # @return [AddSourceResponse]
  describe 'add_a_payment_source test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
