=begin
#Checkout.com API Reference

## Introduction Checkout.com provides a collection of APIs that enable you to process and manage payments.    Our APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors. You can consume the APIs directly using your favorite HTTP/REST library or make use of one of our <a href=\"https://docs.checkout.com/quickstart/integrate/sdks\" target=\"_blank\">SDKs</a>.    Our unified payments API allows you to accept payments from cards, digital wallets and the most popular alternative payment methods, as well as pay out to a variety of destinations, all using the same integration.  And with our webhook management, events and disputes APIs, you can keep on top of your transactions and react to any chargebacks, keeping your business running smoothly. # Authentication When you sign up for an account, you are given a secret and public API key pair. You authenticate with our API by providing the appropriate key in the request Authorization header.  Never share your secret keys. Keep them guarded and secure.   <!-- ReDoc-Inject: <security-definitions> --> 

The version of the OpenAPI document: 1.0.0
Contact: support@checkout.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'cgi'

module OpenapiClient
  class SourcesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Add a payment source
    # Add a reusable payment source, like a <a href=\"https://docs.checkout.com/payment-methods/direct-debit/sepa-direct-debit\" target=\"blank\">SEPA Direct Debit</a>, that you can later use to make one or more payments. Payment sources are linked to a specific customer and cannot be shared between customers. 
    # @param [Hash] opts the optional parameters
    # @option opts [SourceRequest] :source_request 
    # @return [AddSourceResponse]
    def add_a_payment_source(opts = {})
      data, _status_code, _headers = add_a_payment_source_with_http_info(opts)
      data
    end

    # Add a payment source
    # Add a reusable payment source, like a &lt;a href&#x3D;\&quot;https://docs.checkout.com/payment-methods/direct-debit/sepa-direct-debit\&quot; target&#x3D;\&quot;blank\&quot;&gt;SEPA Direct Debit&lt;/a&gt;, that you can later use to make one or more payments. Payment sources are linked to a specific customer and cannot be shared between customers. 
    # @param [Hash] opts the optional parameters
    # @option opts [SourceRequest] :source_request 
    # @return [Array<(AddSourceResponse, Integer, Hash)>] AddSourceResponse data, response status code and response headers
    def add_a_payment_source_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SourcesApi.add_a_payment_source ...'
      end
      # resource path
      local_var_path = '/sources'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'source_request'])

      # return_type
      return_type = opts[:debug_return_type] || 'AddSourceResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiSecretKey']

      new_options = opts.merge(
        :operation => :"SourcesApi.add_a_payment_source",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SourcesApi#add_a_payment_source\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
